### ISSUE TITLE
Suggested changes in meeting on 8th Aug 2022 (faculty meet)

### ISSUE THREAD

**Issue by harimurugan1989** [ravinder-chadha/institute-website#25]
- 48th --> th in superscirpt.. similar for other rankings **(completed)**

- slider arrows in top section.. similar to iitd design.. 

- hover effect on tiles in the top section along with bookmarking for different sections **(Bookmarking yet to be completed)**

- change image in latest news to get the feel of transition. **(completed)**

- auto rolling in latest news

- view all notices in notice section **(completed)**

- Backend work: pin option in notices.. check nitk surathkal website notices

- Director's note title shall be changed to director message **(completed)**

- Name has to be darkened **(completed)**

- Check the font of text message.. it has to be same as that of other section. **(completed)**

- view full message in director section **(completed)**

- Add Bachelor of technoloy, master of technology as a heading in each tab (in larger section)

- FAQs border has to be in line with larger tab section **(completed)**

- Rename the lastest reserach as Research highlights **(completed)**

- latest research icon  and publications icon color to be made blue **(completed)**

- three cards has to be changed at a time as we click the arrows 

- view all in this section has to be left aligned similar to latest news section

- change support nitj to testimonials

- View all in the clubs and socities has to be in line with view gallery **(completed)**

- social media icons to be made colorful in the footer **(not looking good so not updated)**

**Comment by ggsingla** [comment]
### Further Progress :
✅ Hover effect on tiles in the top section along with bookmarking for different sections
✅ Change image in latest news to get the feel of transition.
✅ View all notices in notice section
✅ FAQs border has to be in line with larger tab section
✅ View all in this section has to be left aligned similar to latest news section
✅ View all in the clubs and societies has to be in line with view gallery
