### ISSUE TITLE
Animations in title icons upon hovering

### ISSUE THREAD

**Issue by harimurugan1989** [ravinder-chadha/institute-website#35]
While hover over any icon (next to title), it can jump once.

**Comment by ggsingla** [comment]
The animation is there in the live site, please specify if that needs to be changed or this was intended.

**Comment by ggsingla** [comment]
The animation is there in the live site, please specify if that needs to be changed or this was intended.

**Comment by harimurugan1989** [comment]
animation is there only for top slider.. all other titles such as latest news, notices, research highlights.. everywhere we can add similar effect!

**Comment by ggsingla** [comment]
@harimurugan1989 check and close
